variable subscript_id {}
variable client_id {}
variable client_secret {}
variable tenant_id {}
variable subnet_address_bastion {}
variable subnet_address_prefix {}
variable "vnet_address_space" {}
variable "sku" {}
variable "sku_name" {}
variable "allocation_method" {}
#variable subnet_address_prefix_02{}
variable env_prefix {}
variable location {}
variable app_service_name {}
variable os_publisher {}
variable os_offer {}
variable os_sku {}
variable os_version {}
variable secret {}